# Generated by Django 4.2.23 on 2025-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('09-11', '9am - 11am'), ('11-13', '11am - 1pm'), ('13-15', '1pm - 3pm'), ('15-17', '3pm - 5pm')], default='09-11', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'time_slot')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
