# Generated by Django 4.2.23 on 2025-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='car_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='car_make_model',
            field=models.CharField(default='', help_text='e.g. Toyota Hilux, BMW 3 Series', max_length=150, verbose_name='Car Make & Model'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_reg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
