# Generated by Django 4.2.23 on 2025-09-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_car_type_booking_car_make_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_make_model',
            field=models.CharField(max_length=150),
        ),
    ]
