# Generated by Django 5.2.6 on 2025-09-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_car_make_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time_slot']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_reg',
            field=models.CharField(blank=True, help_text='e.g., ABC-1234', max_length=20, null=True),
        ),
    ]
