# Generated by Django 5.2.6 on 2025-09-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_options_alter_booking_car_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('08:00', '08:00 AM'), ('10:00', '10:00 AM'), ('12:00', '12:00 PM'), ('14:00', '02:00 PM'), ('16:00', '04:00 PM')], max_length=50),
        ),
    ]
