# Generated by Django 5.2.6 on 2025-09-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_reg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
